source: out
paths:
  uploads: uploads
  collections: content
  data: _data
collections_config:
  pages:
    path: content/pages
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: content/posts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading:
    collections:
_enabled_editors:
  - visual
  - content
  - data
_inputs:
  title:
    type: text
    label: Title
    cascade: true
  date:
    type: date
    label: Publish Date
    cascade: true
  content:
    type: markdown
    label: Content
    cascade: true
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold:
    copyformatting:
    italic:
    link:
    paths:
    redo:
    removeformat:
    strike:
    subscript:
    superscript:
    underline:
    undo:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    format: markdown
    image_size_attributes: true
    resize_style: contain
base_url: https://adroit-cucumber.cloudvent.net
editor:
  default_path: https://adroit-cucumber.cloudvent.net
timezone: Etc/UTC
