s# Basic CloudCannon configuration
paths: /public
  uploads: uploads # Specify where uploaded files should go
  data: _data # Specify where data files are located
  collections: content # Specify where your content files are located

# Configure collections (adjust according to your content structure)
collections_config:
  pages:
    path: content/pages
    output: true
  posts:
    path: content/posts
    output: true

# Define editable regions
_editables:
  content:
    format: markdown

# Configure the CloudCannon editor
_inputs:
  title:
    type: text
    label: Title
  date:
    type: date
    label: Publish Date
  content:
    type: markdown
    label: Content
